[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "blograph"
version = "0.1.0"

[dependencies]
chrono = "0.3.0"
iso8601 = "0.1.1"
lazy_static = "0.2.2"
num-traits = "0.1.36"
regex = "0.2.1"
yaml-rust = "0.3.5"
