[package]
authors = ["FeÌlix Saparelli <felix@passcod.name>"]
name = "blograph"
version = "0.1.0"

[dependencies]
chrono = "0.3.0"
git2 = "0.6.4"
lazy_static = "0.2.2"
regex = "0.2.1"
yaml-rust = "0.3.5"
